### ISSUE TITLE
Support color in terminals

### ISSUE THREAD

**Issue by oppegard** [thewoolleyman/process_helper#1]
When using the ruby `system` method to shell out, it sets the correct options to preserve color in the output. For example `system(rspec --color)`. ProcessHelper should do the same. 

Looking at the [RSpec code](https://github.com/rspec/rspec-core/blob/19761e35a0fa8e7d61eaf4af52226fa0c2a39817/lib/rspec/core/configuration.rb#L1826), it uses the `#tty?` method to determine if color is supported, which is usually [`IO#tty?`](http://ruby-doc.org/core-2.3.0/IO.html#method-i-tty-3F) on `$stdout`.

In this specific instance, RSpec can be forced to use color by adding the `--tty` option in addition to `--color`; since ProcessHelper is intended for use on any command, it's best to support color output rather than figure out one-off overrides for every command.

* Perhaps relevant: https://github.com/rails/spring/commit/95bca400877ffa9a21808d9b393bdd5660dc06b0

**Comment by thewoolleyman** [comment]
Do you have any idea what the fix should be to support color output?

**Comment by thewoolleyman** [comment]
I believe this bug is specific to Rspec, because it attempts to detect if it is running in a tty, and if not it will not output color.

Basic printing of color works fine, and I've added some tests to prove it in the [latest commit](https://github.com/thewoolleyman/process_helper/commit/c05f28d3d13e016e54df5434a3f67969a186bcd2).

I might be able to add an option to use a [Pseudo TTY](http://ruby-doc.org/stdlib-2.2.3/libdoc/pty/rdoc/PTY.html), but I'm not sure if this would work in all cases, since capturing output doesn't behave like a TTY in all aspects, and also not sure if it's compatible with [Open3#popen2e](http://ruby-doc.org/stdlib-2.2.1/libdoc/open3/rdoc/Open3.html#method-c-popen2e), which is the crux of how ProcessHelper works.

**Comment by thewoolleyman** [comment]
As you said [this rspec issue](https://github.com/rspec/rspec-core/issues/665) describes this situation exactly, and you can force rspec to color even on non-tty by adding `--tty`.

So, I'm not sure why Kernel#system reports as a tty while Open3#popen2e does not, or if it is overrideable by a Pseudo TTY or other means.

**Comment by oppegard** [comment]
I think the crux of the issue is making processes think they're in a TTY. This is how they detect whether or not to use color in their output. Primary examples of losing color are the `bosh` and `cf` CLIs.

**Comment by oppegard** [comment]
You might look at https://github.com/stripe/subprocess. I tried the following and it outputs color:

```bash
$ gem install subproccess
$ ruby -rsubprocess -e "Subprocess.check_call(['cf', 'apps'])"
# ...(it fails because I'm not authenticated to CF)...
$ echo $?
1
```

**Comment by thewoolleyman** [comment]
As of https://github.com/thewoolleyman/process_helper/commit/9cadff10e37f89b3c09ee8f96cb9abcd8bfd766c, color now works if you invoke the command in a pseudo terminal via the `pseudo_terminal: true` (`pty: true`) option.
